# Generated by Django 4.1.4 on 2022-12-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tictac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wl', models.CharField(max_length=5)),
                ('board', models.CharField(max_length=4)),
            ],
        ),
    ]
