# Generated by Django 4.1.4 on 2022-12-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40, null=True)),
                ('lname', models.CharField(max_length=40, null=True)),
                ('age', models.IntegerField(default=1)),
                ('gender', models.BooleanField(default=True)),
            ],
        ),
    ]
